# Generated by Django 4.1.6 on 2023-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_userschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='Новый пользователь', max_length=255, verbose_name='Полное имя'),
        ),
    ]
