# Generated by Django 4.1.6 on 2023-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schoolName',
            field=models.CharField(default='Новая школа', max_length=255, verbose_name='Название школы'),
        ),
    ]
